//
//  TodaysTrainingView.swift
//  Ollie-app
//
//  Dynamic "Today's Training" view showing an algorithmically generated
//  session plan mixing warm-up, focus skills, maintenance, and easy finish.
//  Based on the 70/30 rule from professional dog training methodology.
//

import SwiftUI
import Combine
import OtisShared

/// Today's Training view - a dynamic session plan generated by the training engine
struct TodaysTrainingView: View {
    @ObservedObject var skillProgressStore: SkillProgressStore
    @ObservedObject var eventStore: EventStore
    @ObservedObject var trainingStore: TrainingPlanStore

    let puppyAgeWeeks: Int
    let onDismiss: () -> Void

    @State private var sessionPlan: TrainingSessionPlan?
    @State private var completedSkillIds: Set<String> = []
    @State private var currentSkillIndex: Int = 0
    @State private var sessionStartTime: Date?
    @State private var elapsedSeconds: Int = 0
    @State private var timerActive: Bool = false
    @State private var showSkillSheet: PrioritizedSkill?
    @State private var showSessionComplete: Bool = false

    @Environment(\.colorScheme) private var colorScheme

    private let timer = Timer.publish(every: 1, on: .main, in: .common).autoconnect()

    // Age-aware session limits
    private var recommendedDuration: (min: Int, max: Int) {
        TrainingEngine.recommendedSessionDuration(puppyAgeWeeks: puppyAgeWeeks)
    }

    private var maxDurationSeconds: Int {
        recommendedDuration.max * 60
    }

    // Progress calculation
    private var totalSkillsInPlan: Int {
        sessionPlan?.allSkillsInOrder.count ?? 0
    }

    private var progressPercentage: Double {
        guard totalSkillsInPlan > 0 else { return 0 }
        return Double(completedSkillIds.count) / Double(totalSkillsInPlan)
    }

    private var isSessionComplete: Bool {
        completedSkillIds.count >= totalSkillsInPlan && totalSkillsInPlan > 0
    }

    var body: some View {
        NavigationStack {
            ScrollView {
                VStack(spacing: 20) {
                    // Session timer and progress
                    sessionHeader

                    if let plan = sessionPlan {
                        if plan.isEmpty {
                            emptyPlanView
                        } else {
                            // Session sections
                            sessionContent(plan: plan)
                        }
                    } else {
                        loadingView
                    }
                }
                .padding()
            }
            .navigationTitle(Strings.Training.todaysTraining)
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .topBarLeading) {
                    Button(Strings.Common.close) {
                        onDismiss()
                    }
                }

                if sessionPlan != nil && !sessionPlan!.isEmpty {
                    ToolbarItem(placement: .topBarTrailing) {
                        Button(action: regeneratePlan) {
                            Image(systemName: "arrow.trianglehead.2.counterclockwise")
                        }
                        .accessibilityLabel("Refresh session plan")
                    }
                }
            }
            .onAppear {
                generatePlan()
            }
            .onReceive(timer) { _ in
                updateTimer()
            }
            .sheet(item: $showSkillSheet) { prioritizedSkill in
                skillLogSheet(for: prioritizedSkill)
            }
            .alert(Strings.Training.sessionComplete, isPresented: $showSessionComplete) {
                Button(Strings.Common.done) {
                    onDismiss()
                }
            } message: {
                Text(Strings.Training.greatWorkMessage)
            }
        }
    }

    // MARK: - Session Header

    private var sessionHeader: some View {
        VStack(spacing: 16) {
            // Timer display
            HStack(spacing: 20) {
                // Elapsed time
                VStack(spacing: 4) {
                    Text(formatTime(elapsedSeconds))
                        .font(.system(size: 32, weight: .bold, design: .rounded))
                        .monospacedDigit()
                        .foregroundStyle(timerColor)

                    Text(Strings.Training.elapsed)
                        .font(.caption)
                        .foregroundStyle(.secondary)
                }

                Divider()
                    .frame(height: 40)

                // Recommended duration
                VStack(spacing: 4) {
                    Text("\(recommendedDuration.min)-\(recommendedDuration.max)")
                        .font(.system(size: 24, weight: .semibold, design: .rounded))

                    Text(Strings.Training.recommendedMinutes)
                        .font(.caption)
                        .foregroundStyle(.secondary)
                }
            }

            // Progress bar
            VStack(spacing: 6) {
                ProgressView(value: progressPercentage)
                    .tint(.otisAccent)

                HStack {
                    Text(Strings.Training.progressLabel(completed: completedSkillIds.count, total: totalSkillsInPlan))
                        .font(.caption)
                        .foregroundStyle(.secondary)

                    Spacer()

                    if elapsedSeconds > maxDurationSeconds {
                        Label(Strings.Training.sessionLong, systemImage: "exclamationmark.triangle.fill")
                            .font(.caption)
                            .foregroundStyle(.orange)
                    }
                }
            }

            // Start/Pause button
            if !timerActive && sessionStartTime == nil {
                Button {
                    startSession()
                } label: {
                    Label(Strings.Training.startSession, systemImage: "play.fill")
                        .font(.headline)
                        .frame(maxWidth: .infinity)
                        .padding(.vertical, 12)
                }
                .buttonStyle(.borderedProminent)
                .tint(.otisAccent)
            }
        }
        .padding()
        .background(
            RoundedRectangle(cornerRadius: 16, style: .continuous)
                .fill(colorScheme == .dark ? Color.white.opacity(0.05) : Color.black.opacity(0.03))
        )
    }

    private var timerColor: Color {
        if elapsedSeconds > maxDurationSeconds {
            return .orange
        } else if elapsedSeconds > recommendedDuration.min * 60 {
            return .green
        }
        return .primary
    }

    // MARK: - Session Content

    @ViewBuilder
    private func sessionContent(plan: TrainingSessionPlan) -> some View {
        VStack(spacing: 16) {
            // 1. Warm-up section (10%)
            if let warmup = plan.warmup {
                sessionSection(
                    title: Strings.Training.warmUp,
                    subtitle: Strings.Training.easyWinToStart,
                    icon: "sun.max.fill",
                    color: .yellow,
                    skills: [warmup]
                )
            }

            // 2. Primary Focus section (60-70%)
            if !plan.primaryFocus.isEmpty {
                let hasPrioritySkills = plan.primaryFocus.contains { $0.priority == .regressionRecovery }
                sessionSection(
                    title: hasPrioritySkills ? Strings.Training.refresherNeeded : Strings.Training.mainFocus,
                    subtitle: hasPrioritySkills ? Strings.Training.regressionFocusSubtitle : Strings.Training.primaryFocusSubtitle,
                    icon: hasPrioritySkills ? "exclamationmark.arrow.circlepath" : "star.fill",
                    color: hasPrioritySkills ? .orange : .otisAccent,
                    skills: plan.primaryFocus
                )
            }

            // 3. Maintenance section (20-30%)
            if !plan.maintenance.isEmpty {
                sessionSection(
                    title: Strings.Training.maintenanceReview,
                    subtitle: Strings.Training.maintenanceSubtitle,
                    icon: "arrow.trianglehead.2.counterclockwise",
                    color: .indigo,
                    skills: plan.maintenance
                )
            }

            // 4. Easy Finish section
            if let finish = plan.easyFinish, finish.id != plan.warmup?.id {
                sessionSection(
                    title: Strings.Training.easyFinish,
                    subtitle: Strings.Training.endOnSuccess,
                    icon: "checkmark.seal.fill",
                    color: .green,
                    skills: [finish]
                )
            }
        }
    }

    @ViewBuilder
    private func sessionSection(
        title: String,
        subtitle: String,
        icon: String,
        color: Color,
        skills: [PrioritizedSkill]
    ) -> some View {
        VStack(alignment: .leading, spacing: 12) {
            // Section header
            HStack(spacing: 8) {
                Image(systemName: icon)
                    .font(.subheadline)
                    .foregroundStyle(color)

                VStack(alignment: .leading, spacing: 2) {
                    Text(title)
                        .font(.headline)
                        .fontWeight(.semibold)

                    Text(subtitle)
                        .font(.caption)
                        .foregroundStyle(.secondary)
                }

                Spacer()
            }

            // Skill cards
            ForEach(skills) { skill in
                sessionSkillCard(skill: skill, tintColor: color)
            }
        }
        .padding()
        .background(
            RoundedRectangle(cornerRadius: 12, style: .continuous)
                .fill(colorScheme == .dark ? Color.white.opacity(0.03) : Color.black.opacity(0.02))
        )
    }

    @ViewBuilder
    private func sessionSkillCard(skill: PrioritizedSkill, tintColor: Color) -> some View {
        let isCompleted = completedSkillIds.contains(skill.id)
        let skillInfo = trainingStore.allSkillsWithStatus.first { $0.skill.id == skill.id }

        Button {
            if !isCompleted {
                showSkillSheet = skill
            }
        } label: {
            HStack(spacing: 12) {
                // Completion indicator
                ZStack {
                    Circle()
                        .stroke(isCompleted ? Color.green : tintColor.opacity(0.3), lineWidth: 2)
                        .frame(width: 28, height: 28)

                    if isCompleted {
                        Image(systemName: "checkmark")
                            .font(.system(size: 14, weight: .bold))
                            .foregroundStyle(.green)
                    } else {
                        Image(systemName: skillInfo?.skill.icon ?? "graduationcap.fill")
                            .font(.system(size: 12))
                            .foregroundStyle(tintColor)
                    }
                }

                // Skill info
                VStack(alignment: .leading, spacing: 2) {
                    Text(skillInfo?.skill.name ?? skill.id)
                        .font(.subheadline)
                        .fontWeight(.medium)
                        .foregroundStyle(isCompleted ? .secondary : .primary)
                        .strikethrough(isCompleted)

                    HStack(spacing: 8) {
                        // Phase badge
                        let phase = skill.progress.phase
                        if phase != .notStarted {
                            Text(phaseLabel(for: phase))
                                .font(.caption2)
                                .foregroundStyle(.secondary)
                        }

                        // Confidence
                        if skill.progress.confidenceScore > 0 {
                            Text(Strings.Training.confidencePercent(Int(skill.progress.confidenceScore * 100)))
                                .font(.caption2)
                                .foregroundStyle(.tertiary)
                        }
                    }
                }

                Spacer()

                // Action indicator
                if !isCompleted {
                    Image(systemName: "chevron.right")
                        .font(.caption)
                        .foregroundStyle(.tertiary)
                }
            }
            .padding(.vertical, 10)
            .padding(.horizontal, 12)
            .background(
                RoundedRectangle(cornerRadius: 10, style: .continuous)
                    .fill(isCompleted
                          ? (colorScheme == .dark ? Color.green.opacity(0.1) : Color.green.opacity(0.05))
                          : (colorScheme == .dark ? Color.white.opacity(0.05) : Color.white))
            )
            .overlay(
                RoundedRectangle(cornerRadius: 10, style: .continuous)
                    .stroke(isCompleted ? Color.green.opacity(0.3) : Color.clear, lineWidth: 1)
            )
        }
        .buttonStyle(.plain)
        .disabled(isCompleted)
    }

    // MARK: - Skill Log Sheet

    @ViewBuilder
    private func skillLogSheet(for prioritizedSkill: PrioritizedSkill) -> some View {
        let skillInfo = trainingStore.allSkillsWithStatus.first { $0.skill.id == prioritizedSkill.id }

        if let skill = skillInfo?.skill {
            TrainingLogSheet(
                skill: skill,
                prefillData: nil,
                onSave: { event in
                    eventStore.addEvent(event)
                    markSkillComplete(prioritizedSkill)
                    showSkillSheet = nil
                },
                onCancel: {
                    showSkillSheet = nil
                },
                onRecordProgress: { skillId, successReps, failedReps, context in
                    skillProgressStore.recordTrainingSession(
                        skillId: skillId,
                        successReps: successReps,
                        failedReps: failedReps,
                        context: context
                    )
                }
            )
            .presentationDetents([.height(580)])
        }
    }

    // MARK: - Empty & Loading States

    private var emptyPlanView: some View {
        VStack(spacing: 16) {
            Image(systemName: "checkmark.circle.fill")
                .font(.system(size: 48))
                .foregroundStyle(.green)

            Text(Strings.Training.noSkillsDue)
                .font(.headline)

            Text(Strings.Training.noSkillsDueMessage)
                .font(.subheadline)
                .foregroundStyle(.secondary)
                .multilineTextAlignment(.center)
        }
        .frame(maxWidth: .infinity)
        .padding(.vertical, 40)
    }

    private var loadingView: some View {
        VStack(spacing: 12) {
            ProgressView()
            Text(Strings.Training.generatingPlan)
                .font(.subheadline)
                .foregroundStyle(.secondary)
        }
        .frame(maxWidth: .infinity)
        .padding(.vertical, 40)
    }

    // MARK: - Helpers

    private func generatePlan() {
        let duration = recommendedDuration.max
        sessionPlan = skillProgressStore.generateSessionPlan(targetDurationMinutes: duration)
    }

    private func regeneratePlan() {
        completedSkillIds.removeAll()
        currentSkillIndex = 0
        generatePlan()
        HapticFeedback.light()
    }

    private func startSession() {
        sessionStartTime = Date()
        timerActive = true
        HapticFeedback.light()
    }

    private func updateTimer() {
        guard timerActive, let startTime = sessionStartTime else { return }
        elapsedSeconds = Int(Date().timeIntervalSince(startTime))
    }

    private func markSkillComplete(_ skill: PrioritizedSkill) {
        completedSkillIds.insert(skill.id)
        currentSkillIndex += 1
        HapticFeedback.success()

        // Check if session is complete
        if isSessionComplete {
            Task { @MainActor in
                try? await Task.sleep(for: .seconds(0.5))
                showSessionComplete = true
                timerActive = false
            }
        }
    }

    private func formatTime(_ seconds: Int) -> String {
        let mins = seconds / 60
        let secs = seconds % 60
        return String(format: "%d:%02d", mins, secs)
    }

    private func phaseLabel(for phase: SkillLearningPhase) -> String {
        switch phase {
        case .notStarted: return ""
        case .luring: return Strings.Training.phaseLuring
        case .addingCue: return Strings.Training.phaseAddingCue
        case .proofing: return Strings.Training.phaseProofing
        case .generalizing: return Strings.Training.phaseGeneralizing
        case .maintaining: return Strings.Training.phaseMaintaining
        case .needsWork: return Strings.Training.phaseNeedsWork
        }
    }
}

// MARK: - Preview

#Preview {
    TodaysTrainingView(
        skillProgressStore: SkillProgressStore(),
        eventStore: EventStore(),
        trainingStore: TrainingPlanStore(),
        puppyAgeWeeks: 12,
        onDismiss: {}
    )
}
